"""initial

Revision ID: 87572d2affec
Revises: dac3cf0ff648
Create Date: 2020-12-09 12:08:32.062436

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '87572d2affec'
down_revision = 'dac3cf0ff648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('login', mysql.VARCHAR(length=16), nullable=True),
                    sa.Column('password', mysql.VARCHAR(length=200), nullable=True),
                    sa.Column('name', mysql.VARCHAR(length=16), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_0900_ai_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    op.create_table('wallet',
                    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('currency', mysql.VARCHAR(length=16), nullable=True),
                    sa.Column('money', mysql.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('owner_id', mysql.INTEGER(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name='wallet_ibfk_1'),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_0900_ai_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    op.create_table('transactions',
                    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('sender_id', mysql.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('receiver_id', mysql.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('sendedmoney', mysql.INTEGER(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['receiver_id'], ['wallet.id'], name='transactions_ibfk_1'),
                    sa.ForeignKeyConstraint(['sender_id'], ['wallet.id'], name='transactions_ibfk_2'),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_0900_ai_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('currency', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('money', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('owner_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name='wallet_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('transactions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sender_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receiver_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sendedmoney', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['wallet.id'], name='transactions_ibfk_1'),
    sa.ForeignKeyConstraint(['sender_id'], ['wallet.id'], name='transactions_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('login', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
